---
- name: nginx install and start services
  hosts: all
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    # - name: start nginx
    #   service: name=nginx state=restarted
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
